global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: blackbox-exporter
    static_configs:
      - targets:
          - blackbox-exporter:9115

  - job_name: proxmox-exporter
    metrics_path: /pve
    params:
      module:
        - default
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/proxmox-exporter.yml
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: proxmox-exporter:9221

  - job_name: cadvisor-monitoring-lxc
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          role: monitoring-lxc

  - job_name: cadvisor-docker
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/cadvisor-docker.yml

  - job_name: node-exporter-proxmox-host
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter-proxmox-host.yml

  - job_name: node-exporter-lxc
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter-lxc.yml

  - job_name: node-exporter-vms
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter-vms.yml

  - job_name: blackbox-http-domains
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://on-prem.jatritech.com
          - https://aspm.jatritech.com
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-tunnel-endpoints
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://on-prem.jatritech.com
          - https://aspm.jatritech.com
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
